name: Push Tag Artifacts to Nexus

on:
  create:
    tags:
      - '*'

jobs:
  push_to_nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Name
        id: get_tag_name
        run: echo ::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}