name: Push Tag Artifacts to Nexus

on:
  create:
    tags:
      - '*'

jobs:
  push_to_nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "name=latest_tag=$latest_tag" >>$GITHUB_OUTPUT

      - name: Get Tag Name
        id: get_tag_name
        run: echo "name=tag_name=${GITHUB_REF/refs\/tags\//}" >>$GITHUB_OUTPUT